version: "3"
services:
  backend:
    build: .
    ports:
      - 3005:3005
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - DB_HOST
      - JWT_SECRET
    volumes:
      - .:/app-backend
    container_name: movies_backend
    restart: always
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD
    restart: always